### ISSUE TITLE
REQ: Tweets

### ISSUE THREAD

**Issue by huphtur** [gfscott/eleventy-plugin-embed-everything#15]
Would love to see support to embed tweets.

So pasting any of these URLs:

- https://twitter.com/gfscott/status/1069966554626850816
- https://twitter.com/gfscott/status/1069966554626850816?s=20

Would result in Twitter embed markup:

```HTML
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hey, I got a sweet new job! Monday was my first day at <a href="https://twitter.com/Shopify?ref_src=twsrc%5Etfw">@Shopify</a>, where I&#39;m going to be working on content strategy in the Apps &amp; Partners ecosystem. There is lots of interesting work to do, and intimidatingly smart people to do it with. It&#39;s going to be good!</p>&mdash; Graham F. Scott (@gfscott) <a href="https://twitter.com/gfscott/status/1069966554626850816?ref_src=twsrc%5Etfw">December 4, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

Note: there are a couple [customization options](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fgfscott%2Fstatus%2F1069966554626850816&widget=Tweet).

**Comment by nhoizey** [comment]
You can already do that with [the `eleventy-plugin-embed-tweet` plugin]( https://github.com/KyleMit/eleventy-plugin-embed-tweet):
https://github.com/KyleMit/eleventy-plugin-embed-tweet#autoembed

**Comment by huphtur** [comment]
Oops, totally missed that plugin, thanks @nhoizey, will dive in.

**Comment by gfscott** [comment]
@huphtur @nhoizey Thanks for opening and helping out with this issue! Glad you found a solution. 

I've now published a new standalone library [`eleventy-plugin-embed-twitter`](https://www.npmjs.com/package/eleventy-plugin-embed-twitter) and rolled it into Embed Everything at [version **1.9.0**](https://github.com/gfscott/eleventy-plugin-embed-everything/releases/tag/v1.9.0).

**Comment by nhoizey** [comment]
@gfscott great! 👍

It's nice having multiple options, with different ways to get a result, everyone can chose.
