### ISSUE TITLE
Repeated YouTube videos

### ISSUE THREAD

**Issue by patrulea** [gfscott/eleventy-plugin-embed-everything#230]
Every instance of YouTube embeds across the build renders the same video.

![image](https://github.com/gfscott/eleventy-plugin-embed-everything/assets/33817380/9944d19e-b6a7-4071-a1ac-e1a198fc2956)

Note how different URLs render the same ID.

---

- **Source code:** https://github.com/patrulea/eleventy-plugin-embed-everything-test
- **Demo:** https://eleventy-plugin-embed-everything-test.netlify.app

**Comment by gfscott** [comment]
Yep, that's just straight-up bug in youtube@1.10.0 and everything@1.18.0. I'll have to revert and release a patch. Thanks for flagging this!

I cloned your example repo and it looks like it works as expected if you use youtube@1.9.1/ everything@1.17.0.

**Comment by gfscott** [comment]
I've [released a patch](https://github.com/gfscott/eleventy-plugin-embed-everything/releases/tag/eleventy-plugin-embed-everything%401.18.1) and validated that it produces the correct output for your test repo. Sorry for the hassle and thanks for filing the issue!
