### ISSUE TITLE
Support dynamic data

### ISSUE THREAD

**Issue by cfjedimaster** [gfscott/eleventy-plugin-embed-everything#48]
Unless I'm missing something, this plugin will only work with a hard coded URL in a MD page, right? What if I wanted to support dynamic data? I've got a page that generates projects, projects include a media URL, and I'd like to do something like:

```
{{ project.mediaUrl | embedEverything }}
```

Possible?

**Comment by gfscott** [comment]
Hey @cfjedimaster, thanks for filing an issue!

My optimistic take is that simply pulling in the URLs with a filter (I'm guessing with `{{ project.mediaUrl }}` on its own) _might_ Just Work™. The plugin uses [transforms](https://www.11ty.dev/docs/config/#transforms), meaning it performs a find-replace operation on Eleventy's HTML **output** — it doesn't get involved with the Markdown parser or the templating engine, and I'm pretty sure transforms are one of the last stops in the processing pipeline.

As long as `{{ project.mediaUrl }}` produces something like this HTML output...

```html
<p>https://example.com/media_url</p>
```

...then this plugin _should_ still work. But your mileage may definitely vary in this case! 

I'm trying to stay pretty focused on the laziest use case with these plugins, which is simple copy-pasting of URLs, so support for filters like you've described isn't on my roadmap right now. But I never say never 😅 

Let me know if the approach above works! I'll leave the issue open for a bit and perhaps we can close the case one way or the other...

**Comment by gfscott** [comment]
Closing this for now, but interested to hear how it turned out!
