### ISSUE TITLE
Only links visible but not posts

### ISSUE THREAD

**Issue by kmyn** [gfscott/eleventy-plugin-embed-everything#52]
Hi,

I'm using this plugin to embed `instagram` and `yoututbe` content in markdown file. Here's my `.eleventy.js` config file -

```
const embedEverything = require("eleventy-plugin-embed-everything");

eleventyConfig.addPlugin(embedEverything, {
    use: ['instagram', 'youtube']
});
```

In the markdown, I'm using -

```
...

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vehicula, elit vel condimentum porta, purus.
 
https://www.instagram.com/p/B9XK4J3jVui/
 
https://www.youtube.com/watch?v=XaCrQL_8eMY

...
```

I just see the text links but no posts. Wondering if someone can help.

Thanks.

**Comment by gfscott** [comment]
The config file looks OK, although it's hard to tell without seeing it all in context. The Markdown file also looks fine. What version of 11ty are you using, and what version of the plugin?

I see two things that could potentially be going wrong here:

1. `eleventyConfig` in `.eleventy.js` might not be implemented properly. I'd suggest taking another look at the [11ty Configuration API docs](https://www.11ty.dev/docs/config/#using-the-configuration-api) — if you're not `module.exports`ing a function that takes `eleventyConfig` as the parameter, then `eleventyConfig` doesn't have any particular meaning.
2. If you're using a different Markdown parser than the one 11ty uses out of the box, it might produce HTML that the plugin doesn't recognize.

Let me know if you work it out! I'll leave this issue open for a couple days so we can share any solutions with future searchers.

**Comment by kmyn** [comment]
Hi @gfscott.

Sorry for the late response. I've used this plugin with NextJS not 11ty. I believe that is the problem. Looks like I missed the 11ty part.

I like this plugin will see if I can get it working with NextJS at some point.

Closing this now. Thank you :)
